# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Set up bin dir
      run: mkdir bin

    - name: Send forge recipes to bin dir
      run: cp ./forge_recipes.json ./bin/forge_recipes.json

    - name: Build Linux
      run: go build -v -o ./bin/sb_forge_calc_linux

    - name: Build Windows
      run: env GOOS=windows GOARCH=amd64 go build -v -o ./bin/sb_forge_calc_win.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: './bin/'
